#!/bin/sh

DAEMON=/usr/bin/aesdsocket

start ()
{
    echo "Starting aesdsocket server"
    start-stop-daemon -S -n aesdsocket -a $DAEMON -d
}

stop ()
{
    echo "Stopping aesdsocket server"
    start-stop-daemon -K -n aesdsocket
}

restart ()
{
    stop
    start
}

[ -e $DAEMON ] || exit 1

case $1 in
	start)
		start;
		;;
	stop)
		stop;
		;;
	restart)
		restart;
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?